import 'dart:io';

void main() {
  final file = File('lib/future/learning/presentation/pages/learning_hub_page.dart');
  var content = file.readAsStringSync();
  content = content.replaceAll(
    'Widget _buildGridCard({\n    required double sc,\n    required String title,\n    required String subtitle,\n    required IconData icon,\n    required Color accentUrl,\n    required String imageUrl,\n    List<Color>? gradientColors,\n    required VoidCallback onTap,\n  }) {\n    return Material(\n      color: Colors.transparent,\n      borderRadius: BorderRadius.circular(20),\n      clipBehavior: Clip.antiAlias,\n      child: InkWell(\n        borderRadius: BorderRadius.circular(20),\n        onTap: onTap,\n        child: Ink(\n          decoration: BoxDecoration(\n            color: UiConstants.primaryButtonColor.withValues(alpha: 0.05),\n            borderRadius: BorderRadius.circular(20),\n            border: Border.all(\n              color: UiConstants.primaryButtonColor.withValues(alpha: 0.15),\n            ),\n            gradient: LinearGradient(\n              colors: gradientColors ?? [\n                UiConstants.secondaryButtonColor.withValues(alpha: 0.8),\n                UiConstants.secondaryButtonColor.withValues(alpha: 0.4),\n              ],\n              begin: Alignment.topLeft,\n              end: Alignment.bottomRight,\n            ),\n            image: DecorationImage(\n              image: AssetImage(imageUrl),\n              fit: BoxFit.cover,\n              colorFilter: ColorFilter.mode(\n                Colors.black.withValues(alpha: 0.2),\n                BlendMode.dstATop,\n              ),\n            ),\n            boxShadow: [\n              BoxShadow(\n                color: UiConstants.secondaryButtonColor.withValues(alpha: 0.2),\n                blurRadius: 8,\n                offset: const Offset(0, 4),\n              ),\n            ],\n          ),\n          child: Padding(\n            padding: EdgeInsets.all(16 * sc),\n            child: Column(\n              crossAxisAlignment: CrossAxisAlignment.start,\n              mainAxisAlignment: MainAxisAlignment.spaceBetween,\n              children: [\n                Container(\n                  padding: EdgeInsets.all(12 * sc),\n                  decoration: BoxDecoration(\n                    color: Colors.white.withValues(alpha: 0.2),\n                    shape: BoxShape.circle,\n                  ),\n                  child: Icon(icon, color: Colors.white, size: 28 * sc),\n                ),',
    'Widget _buildGridCard({\n    required double sc,\n    required String title,\n    required String subtitle,\n    required IconData icon,\n    required Color accentUrl,\n    required String imageUrl,\n    List<Color>? gradientColors,\n    required VoidCallback onTap,\n  }) {\n    final baseColor = gradientColors?.first ?? UiConstants.primaryButtonColor;\n    return Material(\n      color: Colors.transparent,\n      borderRadius: BorderRadius.circular(20),\n      clipBehavior: Clip.antiAlias,\n      child: InkWell(\n        borderRadius: BorderRadius.circular(20),\n        onTap: onTap,\n        child: Ink(\n          decoration: BoxDecoration(\n            color: baseColor.withValues(alpha: 0.1),\n            borderRadius: BorderRadius.circular(20),\n            border: Border.all(\n              color: baseColor.withValues(alpha: 0.3),\n            ),\n            image: DecorationImage(\n              image: AssetImage(imageUrl),\n              fit: BoxFit.cover,\n              colorFilter: ColorFilter.mode(\n                Colors.black.withValues(alpha: 0.2),\n                BlendMode.dstATop,\n              ),\n            ),\n            boxShadow: [\n              BoxShadow(\n                color: baseColor.withValues(alpha: 0.1),\n                blurRadius: 8,\n                offset: const Offset(0, 4),\n              ),\n            ],\n          ),\n          child: Padding(\n            padding: EdgeInsets.all(16 * sc),\n            child: Column(\n              crossAxisAlignment: CrossAxisAlignment.start,\n              mainAxisAlignment: MainAxisAlignment.spaceBetween,\n              children: [\n                Container(\n                  padding: EdgeInsets.all(12 * sc),\n                  decoration: BoxDecoration(\n                    color: baseColor.withValues(alpha: 0.2),\n                    shape: BoxShape.circle,\n                  ),\n                  child: Icon(icon, color: baseColor, size: 28 * sc),\n                ),'
  );
  file.writeAsStringSync(content);
}
