import 'dart:io';

void main() {
  final file = File('lib/future/learning/presentation/pages/learning_hub_page.dart');
  var content = file.readAsStringSync();
  content = content.replaceAll(
    'decoration: BoxDecoration(\n            color: baseColor.withValues(alpha: 0.1),\n            borderRadius: BorderRadius.circular(20),\n            border: Border.all(\n              color: baseColor.withValues(alpha: 0.3),\n            ),\n            image: DecorationImage(\n              image: AssetImage(imageUrl),\n              fit: BoxFit.cover,\n              colorFilter: ColorFilter.mode(\n                Colors.black.withValues(alpha: 0.2),\n                BlendMode.dstATop,\n              ),\n            ),\n            boxShadow: [\n              BoxShadow(\n                color: baseColor.withValues(alpha: 0.1),\n                blurRadius: 8,\n                offset: const Offset(0, 4),\n              ),\n            ],\n          ),\n          child: Padding(\n            padding: EdgeInsets.all(16 * sc),\n            child: Column(\n              crossAxisAlignment: CrossAxisAlignment.start,\n              mainAxisAlignment: MainAxisAlignment.spaceBetween,\n              children: [\n                Container(\n                  padding: EdgeInsets.all(12 * sc),\n                  decoration: BoxDecoration(\n                    color: baseColor.withValues(alpha: 0.2),\n                    shape: BoxShape.circle,\n                  ),\n                  child: Icon(icon, color: baseColor, size: 28 * sc),\n                ),',
    'decoration: BoxDecoration(\n            color: baseColor.withValues(alpha: 0.25),\n            borderRadius: BorderRadius.circular(20),\n            border: Border.all(\n              color: baseColor.withValues(alpha: 0.6),\n              width: 1.5,\n            ),\n            image: DecorationImage(\n              image: AssetImage(imageUrl),\n              fit: BoxFit.cover,\n              colorFilter: ColorFilter.mode(\n                Colors.black.withValues(alpha: 0.35),\n                BlendMode.dstATop,\n              ),\n            ),\n            boxShadow: [\n              BoxShadow(\n                color: baseColor.withValues(alpha: 0.25),\n                blurRadius: 16,\n                offset: const Offset(0, 8),\n              ),\n            ],\n          ),\n          child: Padding(\n            padding: EdgeInsets.all(16 * sc),\n            child: Column(\n              crossAxisAlignment: CrossAxisAlignment.start,\n              mainAxisAlignment: MainAxisAlignment.spaceBetween,\n              children: [\n                Container(\n                  padding: EdgeInsets.all(12 * sc),\n                  decoration: BoxDecoration(\n                    color: baseColor.withValues(alpha: 0.4),\n                    shape: BoxShape.circle,\n                    boxShadow: [\n                      BoxShadow(\n                        color: baseColor.withValues(alpha: 0.3),\n                        blurRadius: 10,\n                        offset: const Offset(0, 4),\n                      ),\n                    ],\n                  ),\n                  child: Icon(icon, color: baseColor.withValues(alpha: 1.0), size: 28 * sc),\n                ),'
  );
  file.writeAsStringSync(content);
}
